source 'https://rubygems.org'


gem 'rails', '4.1.6'
gem 'pg'
gem 'bower-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails'

end
